{
 "title": "Torch",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "loki_ds", "label": "logs datasource", "query": "loki" },
   {
    "name": "service_name",
    "label": "service_name",
    "query": {
     "query": "label_values(ml_pipeline_push_to_blob_runs_total,service_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "sklearn MAE",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ml_training_sklearn_mae{service_name=\"$service_name\"}",
     "legendFormat": "{{model_type}}"
    }
   ]
  },
  {
   "title": "sklearn MAE",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "ml_training_sklearn_mae{service_name=\"$service_name\"}",
     "legendFormat": "{{model_type}}"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "sklearn RMSE",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "ml_training_sklearn_rmse{service_name=\"$service_name\"}",
     "legendFormat": "{{model_type}}"
    }
   ]
  },
  {
   "title": "sklearn RMSE",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ml_training_sklearn_rmse{service_name=\"$service_name\"}",
     "legendFormat": "{{model_type}}"
    }
   ]
  },
  { "title": "📦 push_to_blob", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "push_to_blob pipeline run nb",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "sum(ml_pipeline_push_to_blob_runs_total{service_name=\"$service_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "push_to_blob failed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "sum(ml_blob_push_failed_total{service_name=\"$service_name\"}) by(service_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "push_to_blob error logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"$service_name\", level=\"ERROR\"}"
    }
   ]
  }
 ]
}