kafka.bootstrap.servers=localhost:19092
kafka.application.id=KafkaStreamPipe
kafka.auto.offset.reset=earliest

topic.metrics.input=metrics_raw
topic.metrics.output=metrics
topic.logs.input=logs_raw
topic.logs.output=logs

log.level=INFO
log.level.kafka=WARN
log.level.kafka.streams=INFO
