{
 "title": "Torch",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "loki_ds", "label": "logs datasource", "query": "loki" },
   {
    "name": "service_name",
    "label": "service_name",
    "query": {
     "query": "label_values(ml_pipeline_push_to_blob_runs_total,service_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "📦 push_to_blob", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "push_to_blob pipeline run nb",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "sum(ml_pipeline_push_to_blob_runs_total{service_name=\"$service_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "push_to_blob failed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "sum(ml_blob_push_failed_total{service_name=\"$service_name\"}) by(service_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "push_to_blob error logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"$service_name\", level=\"ERROR\"}"
    }
   ]
  }
 ]
}