from enum import Enum

PROJECT_NAME = "dl_obs"


class DatasourceKind(Enum):
    PROMETHEUS = "prometheus"
    LOKI = "loki"
    TEMPO = "tempo"


class Time(Enum):
    HOUR = 3600
    DAY = 3600 * 24
    WEEK = 3600 * 24 * 7
    MONTH = 3600 * 24 * 30


DEFAULT_AZ_FILE_PREFIX = "chunk"
DEFAULT_AZ_FILE_IDENTIFIER = "dataframe"
DEFAULT_AZ_FILE_EXTENSION = "parquet"

DEFAULTS_LIMITS_OFFSET_DAYS = 0
DEFAULTS_LIMITS_TRAINING_WINDOW_DAYS = 90
DEFAULTS_LIMITS_DF_SPLIT_SIZE = 0.15
DEFAULT_LIMITS_TARGET_COL_NAME = "target"

DEFAULT_S3_FILE_PREFIX = "chunk"
DEFAULT_S3_FILE_IDENTIFIER = "dataframe"
DEFAULT_S3_FILE_EXTENSION = "parquet"

CONFIG_PROM_KEY = "prometheus"
CONFIG_LOKI_KEY = "loki"

# DATA SAVING
OUTPUT_DIR = "output"
DATA_DIR = "data"
DEFAULT_AGG_INTERVAL_MS = 60_000

# MODEL GENERATION
TRAINING_TIMEWINDOW_DAYS = 3
